[FIX] account_financial_report fix to take the id of the currency if is set, that fix the following error:  opt/odoo/odoo/odoo/models.py", line 3681, in write     field.write(self, vals[fname])   File "/opt/odoo/odoo/odoo/fields.py", line 3057, in write     return self.write_batch([(records, value)])   File "/opt/odoo/odoo/odoo/fields.py", line 3078, in write_batch     return self.write_real(records_commands_list, create)   File "/opt/odoo/odoo/odoo/fields.py", line 3254, in write_real     flush()   File "/opt/odoo/odoo/odoo/fields.py", line 3216, in flush     comodel.create(to_create)   File "<decorator-gen-69>", line 2, in create   File "/opt/odoo/odoo/odoo/api.py", line 348, in _model_create_multi     return create(self, arg)   File "/opt/odoo/odoo/odoo/addons/base/models/ir_fields.py", line 534, in create     recs = super().create(vals_list)   File "<decorator-gen-13>", line 2, in create   File "/opt/odoo/odoo/odoo/api.py", line 348, in _model_create_multi     return create(self, arg)   File "/opt/odoo/odoo/odoo/models.py", line 3886, in create     records = self._create(data_list)   File "/opt/odoo/odoo/odoo/models.py", line 3992, in _create     cr.execute(query, params)   File "<decorator-gen-3>", line 2, in execute   File "/opt/odoo/odoo/odoo/sql_db.py", line 101, in check     return f(self, *args, **kwargs)   File "/opt/odoo/odoo/odoo/sql_db.py", line 301, in execute     res = self._obj.execute(query, params) Exception
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.ProgrammingError: can't adapt type 'res.currency'